# Generated by Django 3.2.9 on 2021-11-16 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id_payment', models.BigAutoField(primary_key=True, serialize=False)),
                ('due_date', models.DateField(verbose_name='Data de vencimento')),
                ('value_original', models.FloatField(max_length=30, verbose_name='Valor original')),
                ('value_new', models.FloatField(max_length=30, verbose_name='Novo Valor')),
                ('status', models.CharField(choices=[('Disponible', 'Disponible'), ('Not_Disponible', 'Not_Disponible'), ('Requested', 'Requested'), ('Released', 'Released'), ('Denied', 'Denied')], default='Disponible', max_length=14)),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'perfil',
                'verbose_name_plural': 'perfis',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('register', models.CharField(max_length=14, primary_key=True, serialize=False, verbose_name='CNPJ')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Empresa')),
                ('address', models.CharField(max_length=100, verbose_name='Endereço')),
                ('email_address', models.EmailField(max_length=100, verbose_name='E-mail')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
            },
        ),
        migrations.CreateModel(
            name='ProviderToProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.provider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profile')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50, verbose_name='Status')),
                ('payment_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.payment')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Pagamento',
                'verbose_name_plural': 'Logs de Pagamentos',
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.provider', verbose_name='Fornecedor'),
        ),
    ]
